server:
  port: 5908
  servlet.context-path: /api/v1

spring:
  application:
    name: gsapi

logging:
  file.name: gsapi.log
  level:
    org:
      springframework:
        web: debug

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
